export type CourseSource = 'iGOT Karmayogi — Demo' | 'NSSTA / TPAC — Demo';
export type CourseDifficulty = 'Beginner' | 'Intermediate' | 'Advanced';
export type TrainingCourse = { id: string; title: string; description: string; provider: string; source: CourseSource; competencies: string[]; targetRoles: string[]; difficulty: CourseDifficulty; duration: string; prerequisites: string[]; type: 'Self-Paced e-Learning' | 'Classroom Workshop' | 'Interactive Sandbox'; };
export interface ITrainingRepository { getAllCourses(): Promise<TrainingCourse[]>; getCoursesByCompetency(competencyId: string): Promise<TrainingCourse[]>; getCoursesByRole(roleId: string): Promise<TrainingCourse[]>; }
export const DEMO_TRAINING_COURSES: TrainingCourse[] = [
{id:'igot_sql_101',title:'SQL & Relational Database Querying for Official Statistics',description:'Master SQL joins, aggregation, subqueries, and window functions for compiling large-scale government survey datasets.',provider:'National Informatics Centre (NIC) / iGOT Karmayogi',source:'iGOT Karmayogi — Demo',competencies:['tech_sql','stat_data_quality'],targetRoles:['stat_analyst','data_analyst','stat_officer'],difficulty:'Intermediate',duration:'8 Hours (Self-Paced)',prerequisites:['Basic Computer Literacy'],type:'Self-Paced e-Learning'},
{id:'nssta_sampling_201',title:'Advanced Sampling Methods & Survey Design Frameworks',description:'Hands-on training in PPS sampling, multi-stage stratified cluster sampling, non-sampling error control, and weights calculation.',provider:'National Statistical Systems Training Academy (NSSTA)',source:'NSSTA / TPAC — Demo',competencies:['stat_survey_design','stat_sampling','stat_data_quality'],targetRoles:['stat_officer','stat_analyst','research_officer'],difficulty:'Intermediate',duration:'3 Days Workshop',prerequisites:['Basic Probability & Statistics'],type:'Classroom Workshop'},
{id:'igot_python_stats',title:'Python for Statistical Computing & Survey Automation',description:'Automate data validation, Pandas data cleaning, micro-data compilation, and statistical analysis using Python.',provider:'Data Informatics & Innovation Division (DIID) / iGOT',source:'iGOT Karmayogi — Demo',competencies:['tech_python','tech_api','stat_data_quality'],targetRoles:['stat_analyst','data_analyst','dir_datascience'],difficulty:'Beginner',duration:'12 Hours (Interactive)',prerequisites:['None'],type:'Interactive Sandbox'},
{id:'nssta_sna_301',title:'System of National Accounts (SNA 2008) & GDP Compilation',description:'Comprehensive walkthrough of GDP, GVA, Gross Fixed Capital Formation, input-output matrices, and base year revisions.',provider:'National Accounts Division (NAD) / NSSTA',source:'NSSTA / TPAC — Demo',competencies:['stat_national_accounts','stat_price_stats','mgt_decision'],targetRoles:['stat_analyst','stat_officer','research_officer'],difficulty:'Advanced',duration:'5 Days Executive Workshop',prerequisites:['Macroeconomics & National Income Concepts'],type:'Classroom Workshop'},
{id:'igot_datavis_dashboards',title:'Interactive Statistical Dashboards & Data Visualization',description:'Design executive dashboards for official statistical releases using modern charting libraries, PowerBI, and Matplotlib.',provider:'iGOT Karmayogi Digital Cell',source:'iGOT Karmayogi — Demo',competencies:['tech_datavis','tech_opendata','mgt_comm'],targetRoles:['data_analyst','stat_analyst','research_officer'],difficulty:'Intermediate',duration:'6 Hours (Self-Paced)',prerequisites:['Python or Excel Basics'],type:'Self-Paced e-Learning'},
{id:'igot_dpdp_privacy',title:'Digital Personal Data Protection (DPDP) Act & Statistical Confidentiality',description:'Government compliance guidelines for micro-data anonymization, data privacy rules, and secure publishing on data.gov.in.',provider:'Ministry of Electronics & IT (MeitY) / iGOT Karmayogi',source:'iGOT Karmayogi — Demo',competencies:['gov_privacy','gov_cybersec','stat_metadata'],targetRoles:['stat_analyst','stat_officer','dir_datascience'],difficulty:'Beginner',duration:'4 Hours (Self-Paced)',prerequisites:['None'],type:'Self-Paced e-Learning'},
{id:'nssta_gis_spatial',title:'GIS Mapping & Spatial Analytics for Economic Censuses',description:'Utilize QGIS and spatial indexing tools to map enterprise locations, agricultural crop clusters, and regional development indices.',provider:'NSSTA & Indian Space Research Organisation (ISRO)',source:'NSSTA / TPAC — Demo',competencies:['tech_gis','stat_agri_stats','stat_ind_stats'],targetRoles:['stat_officer','data_analyst','dir_datascience'],difficulty:'Intermediate',duration:'3 Days Hands-on Workshop',prerequisites:['Basic Cartography & Geo-data concepts'],type:'Classroom Workshop'},
{id:'igot_aiml_gov',title:'Applied AI & NLP for Official Data Verification',description:'Machine learning techniques for automatic error detection, NLP for text responses in survey schedules, and anomaly detection.',provider:'Data Science Division / iGOT Karmayogi',source:'iGOT Karmayogi — Demo',competencies:['tech_aiml','tech_cloud','gov_dpi'],targetRoles:['data_analyst','dir_datascience'],difficulty:'Advanced',duration:'16 Hours (Advanced Track)',prerequisites:['Python & Basic Linear Algebra'],type:'Interactive Sandbox'},
{id:'nssta_price_index',title:'Compilation of CPI & WPI Price Statistics',description:'Methodology for Consumer Price Index compilation, basket weighting, price quotation validation, and inflation rate calculations.',provider:'Economic Statistics Division (ESD) / NSSTA',source:'NSSTA / TPAC — Demo',competencies:['stat_price_stats','stat_labour_stats','research_officer'],targetRoles:['stat_analyst','research_officer'],difficulty:'Intermediate',duration:'2 Days Workshop',prerequisites:['Basic Price Index Theory'],type:'Classroom Workshop'},
{id:'igot_public_leadership',title:'Public Sector Leadership & Evidence-Based Governance',description:'Communicating statistical evidence to policymakers, driving digital change in statistical offices, and public project management.',provider:'Capacity Building Commission (CBC) / iGOT Karmayogi',source:'iGOT Karmayogi — Demo',competencies:['mgt_leadership','mgt_comm','mgt_proj_mgt','mgt_change'],targetRoles:['stat_officer','dir_datascience','research_officer'],difficulty:'Intermediate',duration:'5 Hours (Self-Paced)',prerequisites:['None'],type:'Self-Paced e-Learning'}
];
export class DemoTrainingRepository implements ITrainingRepository { async getAllCourses(){return DEMO_TRAINING_COURSES;} async getCoursesByCompetency(competencyId:string){return DEMO_TRAINING_COURSES.filter(c=>c.competencies.includes(competencyId));} async getCoursesByRole(roleId:string){return DEMO_TRAINING_COURSES.filter(c=>c.targetRoles.includes(roleId));} }
export const trainingRepository = new DemoTrainingRepository();