import { useState } from 'react';
import { ShieldCheck, ArrowRight, UserRound, Award, Building2, Briefcase } from 'lucide-react';
import { DEMO_ROLES } from '../lib/competencyFramework';
export type ProfileData = {
  name: string;
  goal: string;
  experience: string;
  designation?: string;
  department?: string;
  currentAssignment?: string;
  yearsOfExperience?: string;
  currentRole?: string;
  targetRole?: string;
  education?: string;
  previousTraining?: string;
};

export function ProfilePage({ profile, setProfile, go }: { profile: ProfileData; setProfile: (p: ProfileData) => void; go: (path: string) => void; }) {
  const [draft, setDraft] = useState<ProfileData>({
    name: profile.name || '', goal: profile.goal || 'Build statistical & analytical tools', experience: profile.experience || 'A little, here and there', designation: profile.designation || 'Senior Statistical Officer', department: profile.department || 'National Accounts Division', currentAssignment: profile.currentAssignment || 'GDP Quarterly Estimates Compilation', yearsOfExperience: profile.yearsOfExperience || '4-7 years', currentRole: profile.currentRole || 'stat_officer', targetRole: profile.targetRole || 'stat_analyst', education: profile.education || 'Master in Statistics / Economics', previousTraining: profile.previousTraining || 'NSSTA Basic Statistical Officer Training (2023)',
  });
  const handleSave = () => { setProfile(draft); localStorage.setItem('pp-profile', JSON.stringify(draft)); go('/diagnostic'); };
  return (
    <div className="mx-auto max-w-4xl space-y-8" data-testid="page-profile">
      <div className="flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-primary">Before we set off</p><h1 className="font-serif text-4xl font-bold tracking-[-.045em] text-foreground sm:text-5xl">Official Learner & Competency Profile</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Configure your official role and background in India's Official Statistical System (MoSPI) to map your personalized competency learning path.</p></div></div>
      <div className="space-y-8 rounded-[1.8rem] border border-border bg-card p-6 shadow-sm sm:p-9">
        <div><h2 className="flex items-center gap-2 font-serif text-xl font-bold text-foreground"><UserRound size={20} className="text-primary" /><span>Learner Identity</span></h2><div className="mt-4 grid gap-6 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="text-sm font-semibold">Full Name</span><input data-testid="input-profile-name" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="e.g. Dr. Rajesh Sharma" className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" /></label><label className="block"><span className="text-sm font-semibold">Primary Goal</span><select data-testid="select-profile-goal" value={draft.goal} onChange={e => setDraft({ ...draft, goal: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:border-primary"><option>Build statistical & analytical tools</option><option>Prepare for a new MoSPI role</option><option>Master Python & Data Science for Statistics</option><option>Enhance Survey & Sampling Methods</option></select></label><label className="block"><span className="text-sm font-semibold">Python & Data Experience</span><select data-testid="select-profile-experience" value={draft.experience} onChange={e => setDraft({ ...draft, experience: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:border-primary"><option>Almost none</option><option>A little, here and there</option><option>I have built small scripts</option><option>I use it regularly</option></select></label></div></div>
        <div className="border-t border-border pt-6"><h2 className="flex items-center gap-2 font-serif text-xl font-bold text-foreground"><Building2 size={20} className="text-primary" /><span>Official Statistical System Profile (MoSPI)</span></h2><div className="mt-4 grid gap-6 sm:grid-cols-2"><label className="block"><span className="text-sm font-semibold">Designation</span><input value={draft.designation} onChange={e => setDraft({ ...draft, designation: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm" /></label><label className="block"><span className="text-sm font-semibold">Department / Division</span><select value={draft.department} onChange={e => setDraft({ ...draft, department: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm"><option>National Accounts Division (NAD)</option><option>Survey Design & Research Division (SDRD)</option><option>Data Informatics & Innovation Division (DIID)</option><option>Economic Statistics Division (ESD)</option><option>Social Statistics Division (SSD)</option><option>Field Operations Division (FOD)</option><option>Other Ministry / Department</option></select></label><label className="block sm:col-span-2"><span className="text-sm font-semibold">Current Assignment</span><input value={draft.currentAssignment} onChange={e => setDraft({ ...draft, currentAssignment: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm" /></label><label className="block"><span className="text-sm font-semibold">Years of Experience</span><select value={draft.yearsOfExperience} onChange={e => setDraft({ ...draft, yearsOfExperience: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm"><option>0-2 years</option><option>2-4 years</option><option>4-7 years</option><option>7-12 years</option><option>12+ years</option></select></label><label className="block"><span className="text-sm font-semibold">Educational Qualification</span><input value={draft.education} onChange={e => setDraft({ ...draft, education: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm" /></label><label className="block sm:col-span-2"><span className="text-sm font-semibold">Previous Training Courses</span><input value={draft.previousTraining} onChange={e => setDraft({ ...draft, previousTraining: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm" /></label></div></div>
        <div className="border-t border-border pt-6"><h2 className="flex items-center gap-2 font-serif text-xl font-bold text-foreground"><Award size={20} className="text-primary" /><span>Target Competency Role Baseline</span></h2><p className="mt-1 text-xs text-muted-foreground">Selecting your target role establishes the required competency thresholds for skill-gap calculation.</p><div className="mt-4 grid gap-6 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="text-sm font-semibold">Target MoSPI Role</span><select data-testid="select-profile-target-role" value={draft.targetRole} onChange={e => setDraft({ ...draft, targetRole: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-4 py-3 text-sm font-semibold text-foreground outline-none focus:border-primary">{DEMO_ROLES.map(role => <option key={role.id} value={role.id}>{role.title} — {role.description}</option>)}</select></label></div></div>
        <div className="mt-8 flex flex-col justify-between gap-4 border-t border-border pt-6 sm:flex-row sm:items-center"><div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={16} className="text-primary" /><span>Saved securely in your browser state</span></div><button onClick={handleSave} data-testid="button-profile-continue" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-bold text-primary-foreground shadow-sm transition hover:brightness-110 active:translate-y-px"><span>Save Profile & Continue to Check-in</span><ArrowRight size={16} /></button></div>
      </div>
    </div>
  );
}
