import { useState } from 'react';
import { Users, AlertTriangle, Building2, TrendingUp, Sparkles, ArrowRight, ShieldCheck, Award } from 'lucide-react';
import { getWorkforceAnalyticsSummary, DEMO_WORKFORCE_LEARNERS } from '../lib/workforceAnalytics';
import { DOMAINS } from '../lib/competencyFramework';
function cx(...classes: (string | false | undefined)[]) {
  return classes.filter(Boolean).join(' ');
}
export function WorkforceAnalytics({ go }: { go: (path: string) => void }) {
  const summary = getWorkforceAnalyticsSummary();
  const [selectedDepartment, setSelectedDepartment] = useState<string>('All Departments');
  const filteredLearners = selectedDepartment === 'All Departments'
    ? DEMO_WORKFORCE_LEARNERS
    : DEMO_WORKFORCE_LEARNERS.filter(l => l.department.includes(selectedDepartment.split(' ')[0]));
  return (
    <div className="space-y-8" data-testid="workforce-analytics">
      <div>
        <h3 className="font-serif text-xl font-bold mb-4">Organizational Competency Domain Health</h3>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <div className="rounded-2xl border border-border bg-card p-5"><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Statistical System</span><p className="mt-2 font-serif text-3xl font-bold text-foreground">{summary.domainAverages.statistical}%</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: `${summary.domainAverages.statistical}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">Survey design & national accounts</p></div>
          <div className="rounded-2xl border border-border bg-card p-5"><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Technical & Data Science</span><p className="mt-2 font-serif text-3xl font-bold text-foreground">{summary.domainAverages.technical}%</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-accent" style={{ width: `${summary.domainAverages.technical}%` }} /></div><p className="mt-2 text-xs text-accent font-semibold">Priority improvement area</p></div>
          <div className="rounded-2xl border border-border bg-card p-5"><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Digital Governance</span><p className="mt-2 font-serif text-3xl font-bold text-foreground">{summary.domainAverages.governance}%</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-[hsl(197_45%_45%)]" style={{ width: `${summary.domainAverages.governance}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">DPDP privacy & MeghRaj cloud</p></div>
          <div className="rounded-2xl border border-border bg-card p-5"><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Managerial & Ethics</span><p className="mt-2 font-serif text-3xl font-bold text-foreground">{summary.domainAverages.managerial}%</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-[hsl(162_46%_35%)]" style={{ width: `${summary.domainAverages.managerial}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">Leadership & evidence ethics</p></div>
        </div>
      </div>
      <div className="rounded-2xl border border-border bg-card p-6 shadow-sm space-y-4">
        <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-accent">Workforce Intelligence</p><h3 className="font-serif text-xl font-bold">Top Organizational Skill Gaps</h3></div><span className="text-xs text-muted-foreground font-semibold">Ranked by overall workforce deficit</span></div>
        <div className="space-y-3">{summary.topOrgSkillGaps.map((gap, idx) => <div key={gap.competencyId} className="flex flex-col justify-between gap-3 rounded-xl border border-border bg-secondary/50 p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="font-mono text-sm font-bold text-muted-foreground">0{idx + 1}</span><div><h4 className="font-serif font-bold text-foreground text-sm">{gap.competencyName}</h4><span className="text-xs text-muted-foreground">Current Avg: <strong className="text-foreground">{gap.avgCurrent}%</strong> vs Required Target: <strong className="text-primary">{gap.avgRequired}%</strong></span></div></div><div className="flex items-center gap-4 text-xs font-semibold"><span className="rounded-full bg-accent/15 px-3 py-1 font-mono text-accent font-bold">-{gap.gap}pt gap</span><span className="text-muted-foreground">{gap.affectedLearnersCount} officers affected</span><button onClick={() => go('/training')} className="inline-flex items-center gap-1 text-primary font-bold hover:underline">View Training →</button></div></div>)}</div>
      </div>
      <div className="rounded-2xl border border-border bg-card p-6 shadow-sm space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 className="font-serif text-xl font-bold">Departmental Breakdown</h3><p className="mt-0.5 text-xs text-muted-foreground">Inspect competency matches by division across MoSPI.</p></div><select value={selectedDepartment} onChange={e => setSelectedDepartment(e.target.value)} className="rounded-xl border border-input bg-background px-3 py-2 text-xs font-semibold outline-none focus:border-primary"><option>All Departments</option><option>National Accounts Division</option><option>Data Informatics & Innovation Division</option><option>Survey Design & Research Division</option><option>Economic Statistics Division</option><option>Social Statistics Division</option><option>Field Operations Division</option></select></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-border text-muted-foreground font-bold uppercase text-[10px] tracking-wider"><th className="pb-3">Officer Name</th><th className="pb-3">Designation</th><th className="pb-3">Department</th><th className="pb-3 text-center">Competency Match</th><th className="pb-3 text-center">Learning Hours</th><th className="pb-3 text-center">Avg Assessment</th></tr></thead><tbody className="divide-y divide-border/60">{filteredLearners.map(l => <tr key={l.id} className="hover:bg-secondary/40"><td className="py-3 font-bold text-foreground">{l.name}</td><td className="py-3 text-muted-foreground">{l.designation}</td><td className="py-3 text-muted-foreground">{l.department}</td><td className="py-3 text-center font-mono font-bold text-primary">{Math.round(Object.values(l.competencies).reduce((a, b) => a + b, 0) / Object.values(l.competencies).length)}%</td><td className="py-3 text-center font-mono">{l.learningHours}h</td><td className="py-3 text-center font-mono font-bold text-[hsl(162_46%_27%)]">{Math.round(l.assessmentScores.reduce((a, b) => a + b, 0) / l.assessmentScores.length)}%</td></tr>)}</tbody></table></div></div>
      <div className="space-y-4"><h3 className="font-serif text-xl font-bold">Actionable Executive Recommendations</h3><div className="grid gap-4 sm:grid-cols-3">{summary.adminRecommendations.map(rec => <div key={rec.id} className="rounded-2xl border border-primary/20 bg-primary/5 p-5 space-y-3 flex flex-col justify-between"><div><span className="inline-flex rounded-full bg-primary px-2.5 py-0.5 text-[10px] font-bold text-primary-foreground uppercase tracking-wider">{rec.priority} Priority</span><h4 className="mt-3 font-serif font-bold text-base text-foreground">{rec.title}</h4><p className="mt-2 text-xs leading-5 text-muted-foreground">{rec.description}</p><p className="mt-2 text-[11px] font-semibold text-primary">Reason: {rec.reason}</p></div><button onClick={() => go('/training')} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground shadow-sm hover:brightness-110"><span>Deploy Training Program</span><ArrowRight size={14} /></button></div>)}</div></div>
    </div>
  );
}
