import { useState } from 'react';
import { Target, Award, AlertCircle } from 'lucide-react';
import { DEMO_ROLES, DOMAINS } from '../lib/competencyFramework';
import { calculateSkillGaps } from '../lib/skillGapEngine';
import { CompetencyCard } from '../components/CompetencyCard';
import { CompetencyRadar } from '../components/CompetencyRadar';
import { SkillGapCard } from '../components/SkillGapCard';

function cx(...classes: (string | false | undefined)[]) { return classes.filter(Boolean).join(' '); }
type ProfileState = { name: string; designation?: string; department?: string; targetRole: string; };

export function CompetencyProfilePage({ profile, setProfile, demonstratedCompetencies, go }: { profile: ProfileState; setProfile: (p: ProfileState) => void; demonstratedCompetencies: Record<string, number>; go: (path: string) => void; }) {
  const [selectedDomain, setSelectedDomain] = useState<string>('all');
  const roleOverview = calculateSkillGaps(profile.targetRole || 'stat_analyst', demonstratedCompetencies);
  const currentRole = roleOverview.role;
  const filteredGaps = selectedDomain === 'all' ? roleOverview.gaps : roleOverview.gaps.filter(g => g.domain === selectedDomain);
  return <div className="mx-auto max-w-6xl space-y-8" data-testid="page-competency-profile">
    <div className="flex flex-col justify-between gap-5 rounded-[1.8rem] border border-border bg-card p-6 shadow-sm sm:p-8 md:flex-row md:items-center">
      <div><div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-bold text-primary"><Award size={14} /><span>MoSPI Competency Framework</span></div><h1 className="mt-3 font-serif text-3xl font-bold tracking-[-.03em] text-foreground sm:text-4xl">Competency Profile & Skill-Gap Intelligence</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Official Statistical System competency analysis comparing your demonstrated signals against role standards.</p></div>
      <div className="min-w-[280px] shrink-0 rounded-2xl border border-border bg-secondary/50 p-4"><label className="block text-xs font-bold uppercase tracking-wider text-muted-foreground">Target Role Baseline</label><select data-testid="select-target-role" value={profile.targetRole || 'stat_analyst'} onChange={e => setProfile({ ...profile, targetRole: e.target.value })} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm font-semibold text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15">{DEMO_ROLES.map(role => <option key={role.id} value={role.id}>{role.title}</option>)}</select><p className="mt-2 text-[11px] text-muted-foreground/80">{currentRole.description}</p></div>
    </div>
    <div className="grid gap-4 sm:grid-cols-3">
      <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-muted-foreground">Overall Role Match</span><Target size={18} className="text-primary" /></div><p className="mt-3 font-serif text-3xl font-bold text-foreground">{roleOverview.overallCompetencyMatch}%</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all duration-500" style={{ width: `${roleOverview.overallCompetencyMatch}%` }} /></div></div>
      <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-muted-foreground">Satisfied Competencies</span><Award size={18} className="text-[hsl(162_46%_27%)]" /></div><p className="mt-3 font-serif text-3xl font-bold text-foreground">{roleOverview.satisfiedCount} <span className="text-base font-sans font-normal text-muted-foreground">/ {roleOverview.totalRequiredCount}</span></p><p className="mt-2 text-xs text-muted-foreground">Competency standards fully met</p></div>
      <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-muted-foreground">Priority Skill Gaps</span><AlertCircle size={18} className="text-accent" /></div><p className="mt-3 font-serif text-3xl font-bold text-foreground">{roleOverview.topPriorityGaps.length}</p><p className="mt-2 text-xs font-semibold text-accent">High & Moderate priority areas</p></div>
    </div>
    <CompetencyRadar gaps={roleOverview.gaps} />
    {roleOverview.topPriorityGaps.length > 0 && <div><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-accent">Skill-Gap Intelligence</p><h2 className="font-serif text-2xl font-bold">Top Priority Skill Gaps</h2></div><span className="text-xs text-muted-foreground">Ranked by role requirement and gap magnitude</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{roleOverview.topPriorityGaps.map(gap => <SkillGapCard key={gap.competencyId} gap={gap} onNavigate={() => go('/roadmap')} />)}</div></div>}
    <div className="space-y-5"><div className="flex flex-col justify-between gap-4 border-b border-border pb-4 sm:flex-row sm:items-center"><div><h2 className="font-serif text-2xl font-bold">Detailed Competency Breakdown</h2><p className="mt-1 text-xs text-muted-foreground">Filter by MoSPI competency domain to inspect demonstrated signals vs required levels.</p></div><div className="flex flex-wrap items-center gap-1.5 rounded-xl border border-border bg-card p-1"><button onClick={() => setSelectedDomain('all')} className={cx('rounded-lg px-3 py-1.5 text-xs font-semibold transition', selectedDomain === 'all' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground')}>All Domains ({roleOverview.gaps.length})</button>{Object.entries(DOMAINS).map(([key, domain]) => { const count = roleOverview.gaps.filter(g => g.domain === key).length; if (!count) return null; return <button key={key} onClick={() => setSelectedDomain(key)} className={cx('rounded-lg px-3 py-1.5 text-xs font-semibold transition', selectedDomain === key ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground')}>{domain.name} ({count})</button>; })}</div></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filteredGaps.map(item => <CompetencyCard key={item.competencyId} item={item} />)}</div></div>
  </div>;
}
